version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_ROOT_HOST: '%'
      MYSQL_SSL_CERT: ${ENVIRONMENT:-development} == 'production' && '/etc/mysql/certs/server-cert.pem' || ''
      MYSQL_SSL_KEY: ${ENVIRONMENT:-development} == 'production' && '/etc/mysql/certs/server-key.pem' || ''
      MYSQL_SSL_CA: ${ENVIRONMENT:-development} == 'production' && '/etc/mysql/certs/ca.pem' || ''
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${ENVIRONMENT:-development} == 'production' && ./mysql/certs:/etc/mysql/certs || ''
    command: >
      mysqld
      ${ENVIRONMENT:-development} == 'production' && 
      --ssl-cert=/etc/mysql/certs/server-cert.pem 
      --ssl-key=/etc/mysql/certs/server-key.pem
      --ssl-ca=/etc/mysql/certs/ca.pem ||
      --skip-ssl
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=api.django.dev
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SIGNING_KEY=${SIGNING_KEY}
      - DISCORD_KEY=${DISCORD_KEY}
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    command: ./bot-entrypoint.sh
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=api.django.dev
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SIGNING_KEY=${SIGNING_KEY}
      - DISCORD_KEY=${DISCORD_KEY}
    depends_on:
      - web
      - db

volumes:
  mysql_data:
