# Database Migrations Configuration
# -------------------------------
# Purpose: Configure database migration behavior
# Features:
# - Logging settings
# - Validation rules
# - Performance tuning
# Author: Renzo Tincopa
# Last Updated: 2024

migrations:
  # Logging configuration
  # Controls migration logging behavior
  logging:
    enabled: ${MIGRATIONS_LOGGING_ENABLED}  # true/false
    level: ${MIGRATIONS_LOGGING_LEVEL}      # DEBUG/INFO/WARNING/ERROR

  # Validation settings
  # Pre-migration checks and validations
  validation:
    check_db_connection: ${MIGRATIONS_VALIDATION_CHECK_DB}   # Verify DB connection
    check_dependencies: ${MIGRATIONS_VALIDATION_CHECK_DEPS}  # Check migration dependencies

  # Performance tuning
  # Settings to optimize migration execution
  performance:
    batch_size: ${MIGRATIONS_PERFORMANCE_BATCH_SIZE}           # Records per batch
    use_transactions: ${MIGRATIONS_PERFORMANCE_USE_TRANSACTIONS} # Enable transaction wrapping
