# Generated by Django 5.1.2 on 2024-12-31 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trivia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trivia",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trivias_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="trivia",
            name="language",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trivias",
                to="trivia.language",
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="trivia",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trivias",
                to="trivia.theme",
                verbose_name="Theme",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="trivia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="trivia.trivia",
                verbose_name="Trivia",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="trivia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="trivia.trivia",
                verbose_name="Trivia",
            ),
        ),
        migrations.AddConstraint(
            model_name="trivia",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_trivia_title"
            ),
        ),
    ]
